image: Visual Studio 2017

install:

- ps: >-
    (New-Object Net.WebClient).DownloadFile('http://www.monogame.net/releases/v3.6/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')
- ps: >-
    Invoke-Command -ScriptBlock {C:\MonoGameSetup.exe /S /v/qn}

before_build:

- ps: >-

    nuget restore
